version: "3.8"

services:
  db:
    container_name: mercedtime-postgres
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: mt
      POSTGRES_DB: mercedtime
    volumes:
      - ./api/db/sql:/docker-entrypoint-initdb.d:ro
      - ./api/db/data:/data:ro
    restart: unless-stopped
    ports:
      - target: 5432
        published: 25432
        protocol: tcp
        mode: bridge

  api:
    container_name: mercedtime-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command:
      - "wait-for" # wait for the database to start
      - 'localhost:25432'
      - "--"
      - "/app/bin/mt"
      - "--driver=postgres"
      - "--port=8080"
      - '--name=mercedtime'
      - '--user=mt'
      - "--db-host=localhost"
      - "--db-port=25432"
    restart: unless-stopped
    # port mapping will be ignored if network_mode=="host"
    network_mode: host
    ports:
      - target: 8080    # in container
        published: 8080 # host
        protocol: tcp
        mode: host
    depends_on:
      - db

  # automatic webscraping and database updates
  cron:
    container_name: mercedtime-cron
    build:
      context: ./api
      dockerfile: docker/Dockerfile.cron
    environment:
      MT_PW: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 25432
    depends_on:
      - db
    network_mode: host
    # command: ["true"] # disable
